<a href="https://colab.research.google.com/github/preetamjumech/LLM/blob/main/AttentionMechanism_17_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
word_1 = tf.constant([[0, 1, 1, 2]])
word_2 = tf.constant([[1, 0, 0, 2]])
word_3 = tf.constant([[1, 1, 0, 2]])
word_4 = tf.constant([[2, 1, 1, 1]])

In [3]:
word_emb_stack = tf.stack([word_1, word_2, word_3, word_4], axis = 1)

word_emb_stack

<tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
array([[[0, 1, 1, 2],
        [1, 0, 0, 2],
        [1, 1, 0, 2],
        [2, 1, 1, 1]]], dtype=int32)>

In [4]:
shape = (4, 4)

W_Q = tf.random.uniform(shape = shape, minval = 0, maxval = 3, dtype = tf.int32)
W_K = tf.random.uniform(shape = shape, minval = 0, maxval = 3, dtype = tf.int32)
W_V = tf.random.uniform(shape = shape, minval = 0, maxval = 3, dtype = tf.int32)

W_Q, W_K, W_V

(<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[0, 1, 1, 1],
        [1, 1, 2, 2],
        [0, 0, 1, 0],
        [0, 1, 0, 0]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[2, 0, 0, 1],
        [2, 0, 2, 1],
        [0, 1, 2, 1],
        [1, 1, 2, 2]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[0, 1, 0, 0],
        [1, 2, 0, 2],
        [0, 1, 1, 1],
        [0, 2, 2, 2]], dtype=int32)>)

In [5]:
# generating the queries, keys and values
query_1 = tf.matmul(word_1, W_Q)
key_1 = tf.matmul(word_1, W_K)
value_1 = tf.matmul(word_1, W_V)

query_2 = tf.matmul(word_2, W_Q)
key_2 = tf.matmul(word_2, W_K)
value_2 = tf.matmul(word_2, W_V)

query_3 = tf.matmul(word_3, W_Q)
key_3 = tf.matmul(word_3, W_K)
value_3 = tf.matmul(word_3, W_V)

query_4 = tf.matmul(word_4, W_Q)
key_4 = tf.matmul(word_4, W_K)
value_4 = tf.matmul(word_4, W_V)

In [6]:
query_1, key_1, value_1

(<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 3, 3, 2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[4, 3, 8, 6]], dtype=int32)>,
 <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 7, 5, 7]], dtype=int32)>)

In [7]:
scores = tf.stack([
    tf.matmul(query_1, key_1, transpose_b = True),
    tf.matmul(query_1, key_2, transpose_b = True),
    tf.matmul(query_1, key_3, transpose_b = True),
    tf.matmul(query_1, key_4, transpose_b = True)]
)

scores

<tf.Tensor: shape=(4, 1, 1), dtype=int32, numpy=
array([[[49]],

       [[32]],

       [[42]],

       [[43]]], dtype=int32)>

In [8]:
weights = tf.nn.softmax(
    tf.cast(tf.squeeze(scores), tf.float32) / tf.math.sqrt(tf.cast(tf.shape(key_1)[-1], tf.float32))
)

weights

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([9.2576486e-01, 1.8836386e-04, 2.7955677e-02, 4.6091117e-02],
      dtype=float32)>

In [9]:
value_1 = tf.cast(value_1, tf.float32)
value_2 = tf.cast(value_2, tf.float32)
value_3 = tf.cast(value_3, tf.float32)
value_4 = tf.cast(value_4, tf.float32)

In [10]:
attention = (weights[0] * value_1) + (weights[1] * value_2) + (weights[2] * value_3) + (weights[3] * value_4)

print(attention)

tf.Tensor([[0.99981165 6.9996233  4.8796735  6.879297  ]], shape=(1, 4), dtype=float32)


In [11]:
word_emb_stack

<tf.Tensor: shape=(1, 4, 4), dtype=int32, numpy=
array([[[0, 1, 1, 2],
        [1, 0, 0, 2],
        [1, 1, 0, 2],
        [2, 1, 1, 1]]], dtype=int32)>

In [12]:
word_emb_stack = tf.squeeze(word_emb_stack)

word_emb_stack

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 1, 2],
       [1, 0, 0, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 1]], dtype=int32)>

In [13]:
Query = word_emb_stack @ W_Q
Key = word_emb_stack @ W_K
Value = word_emb_stack @ W_V

Query, Key, Value

(<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[1, 3, 3, 2],
        [0, 3, 1, 1],
        [1, 4, 3, 3],
        [1, 4, 5, 4]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[4, 3, 8, 6],
        [4, 2, 4, 5],
        [6, 2, 6, 6],
        [7, 2, 6, 6]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[1, 7, 5, 7],
        [0, 5, 4, 4],
        [1, 7, 4, 6],
        [1, 7, 3, 5]], dtype=int32)>)

In [14]:
scores = tf.matmul(Query, Key, transpose_b = True)

scores

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[49, 32, 42, 43],
       [23, 15, 18, 18],
       [58, 39, 50, 51],
       [80, 52, 68, 69]], dtype=int32)>

In [15]:
weights = tf.nn.softmax(tf.cast(scores, tf.float32) / tf.math.sqrt(tf.cast(tf.shape(Key)[-1], tf.float32)))

weights

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[9.2576486e-01, 1.8836386e-04, 2.7955677e-02, 4.6091121e-02],
       [8.4567618e-01, 1.5489100e-02, 6.9417328e-02, 6.9417328e-02],
       [9.5366347e-01, 7.1383452e-05, 1.7466957e-02, 2.8798142e-02],
       [9.9347657e-01, 8.2610433e-07, 2.4625824e-03, 4.0601119e-03]],
      dtype=float32)>

In [16]:
attention = tf.matmul(weights, tf.cast(Value, tf.float32))

attention

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.99981165, 6.9996233 , 4.8796735 , 6.8792973 ],
       [0.9845109 , 6.9690213 , 4.776259  , 6.74528   ],
       [0.9999286 , 6.999857  , 4.924865  , 6.924722  ],
       [0.9999992 , 6.999999  , 4.989417  , 6.989415  ]], dtype=float32)>