<a href="https://colab.research.google.com/github/preetamjumech/LLM/blob/main/Check_Hallucination_of_LLMs_and_RAGs_using_Open_Source_Evaluation_Model_by_Vectara_07_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from transformers import AutoModelForSequenceClassification

In [6]:
pairs = [ ["A man walks into a bar and buys a drink", "A bloke swigs alcohol at a pub"],
          ["A person on a horse jumps over a broken down airplane.", "A person is at a diner, ordering an omelette."],
          ["A person on a horse jumps over a broken down airplane.", "A person is outdoors, on a horse."],
          ["A boy is jumping on skateboard in the middle of a red bridge.", "The boy skates down the sidewalk on a blue bridge"],
          ["A man with blond-hair, and a brown shirt drinking out of a public water fountain.", "A blond drinking water in public."],
          ["A man with blond-hair, and a brown shirt drinking out of a public water fountain.", "A blond man wearing a brown shirt is reading a book."],
          ["Mark Wahlberg was a fan of Manny.", "Manny was a fan of Mark Wahlberg."]
      ]

In [8]:
model = AutoModelForSequenceClassification.from_pretrained(
    'vectara/hallucination_evaluation_model', trust_remote_code=True)

# Step 2: Use the model to predict
scores = model.predict(pairs)
scores

You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.


tensor([0.0852, 0.0114, 0.8969, 0.0061, 0.9677, 0.0050, 0.0543])

In [10]:
import numpy as np

# Convert the values to one decimal point
score_one_decimal = np.around(scores, decimals=1)

# Convert the values to percentage with one decimal point
score_percentage = np.around(scores * 100, decimals=1)
print(score_one_decimal)
print(score_percentage)

tensor([0.1000, 0.0000, 0.9000, 0.0000, 1.0000, 0.0000, 0.1000])
tensor([ 8.5000,  1.1000, 89.7000,  0.6000, 96.8000,  0.5000,  5.4000])
