<a href="https://colab.research.google.com/github/preetamjumech/LLM/blob/main/NLP_with_LLMS_25_09_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.3/474.3 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 16.5 MB/s eta 0:00:00
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.


In [ ]:
from transformers import pipeline
train_pipeline = pipeline("translation_en_to_de", model="t5-small") #60 million paramters
train_pipeline

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [ ]:
import evaluate
bleu  = evaluate.load("bleu")
bleu

EvaluationModule(name: "bleu", module_type: "metric", features: [{'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}, {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')}], usage: """
Computes BLEU score of translated segments against one or more references.
Args:
    predictions: list of translations to score.
    references: list of lists of or just a list of references for each translation.
    tokenizer : approach used for tokenizing `predictions` and `references`.
        The default tokenizer is `tokenizer_13a`, a minimal tokenization approach that is equivalent to `mteval-v13a`, used by WMT.
        This can be replaced by any function that takes a string as input and returns a list of tokens as output.
    max_order: Maximum n-gram order to use when computing BLEU score.
    smooth: Whether or not to apply Lin et al. 2004 smoot

In [ ]:
reference = {
    "Ich liebe Fußball"
}

In [ ]:
text = "I love football"
result = train_pipeline(text)
print(result)

[{'translation_text': 'Ich liebe Fußball'}]


In [ ]:
prediction = result[0]["translation_text"]
prediction

'Ich liebe Fußball'

In [ ]:
score = bleu.compute(predictions=[prediction], references=[reference])
score

{'bleu': 0.0,
 'precisions': [1.0, 1.0, 1.0, 0.0],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0,
 'translation_length': 3,
 'reference_length': 3}

In [ ]:
train_pipeline = pipeline("translation_en_to_de", model="t5-base") #220 million paramters
train_pipeline

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [ ]:
text = "I love football"
result = train_pipeline(text)
print(result)

[{'translation_text': 'Ich liebe Fußball'}]


In [ ]:
prediction = result[0]["translation_text"]
prediction

'Ich liebe Fußball'

In [ ]:
score = bleu.compute(predictions=[prediction], references=[reference])
score

{'bleu': 0.0,
 'precisions': [1.0, 1.0, 1.0, 0.0],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0,
 'translation_length': 3,
 'reference_length': 3}

In [ ]:
!pip install sentencepiece

In [ ]:
train_pipeline1 = pipeline(task = "text2text-generation", model = "facebook/m2m100_418M")
train_pipeline1

In [ ]:
train_pipeline1.tokenizer.get_lang_id

<bound method M2M100Tokenizer.get_lang_id of M2M100Tokenizer(name_or_path='facebook/m2m100_418M', vocab_size=128004, model_max_length=1024, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'additional_special_tokens': ['__af__', '__am__', '__ar__', '__ast__', '__az__', '__ba__', '__be__', '__bg__', '__bn__', '__br__', '__bs__', '__ca__', '__ceb__', '__cs__', '__cy__', '__da__', '__de__', '__el__', '__en__', '__es__', '__et__', '__fa__', '__ff__', '__fi__', '__fr__', '__fy__', '__ga__', '__gd__', '__gl__', '__gu__', '__ha__', '__he__', '__hi__', '__hr__', '__ht__', '__hu__', '__hy__', '__id__', '__ig__', '__ilo__', '__is__', '__it__', '__ja__', '__jv__', '__ka__', '__kk__', '__km__', '__kn__', '__ko__', '__lb__', '__lg__', '__ln__', '__lo__', '__lt__', '__lv__', '__mg__', '__mk__', '__ml__', '__mn__', '__mr__', '__ms__', '__my__', '__ne__', '__nl__', '__no__', '__ns__', '__oc__', '__or__', '__pa__', '__pl__', '__ps__', '__pt__', '__ro__', '__ru__', '__sd__', '__si__', '__sk__', '__sl__', '__so__', '__sq__', '__sr__', '__ss__', '__su__', '__sv__', '__sw__', '__ta__', '__th__', '__tl__', '__tn__', '__tr__', '__uk__', '__ur__', '__uz__', '__vi__', '__wo__', '__xh__', '__yi__', '__yo__', '__zh__', '__zu__']}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128004: AddedToken("__af__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128005: AddedToken("__am__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128006: AddedToken("__ar__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128007: AddedToken("__ast__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128008: AddedToken("__az__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128009: AddedToken("__ba__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128010: AddedToken("__be__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128011: AddedToken("__bg__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128012: AddedToken("__bn__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128013: AddedToken("__br__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128014: AddedToken("__bs__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128015: AddedToken("__ca__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128016: AddedToken("__ceb__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128017: AddedToken("__cs__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128018: AddedToken("__cy__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128019: AddedToken("__da__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128020: AddedToken("__de__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128021: AddedToken("__el__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128022: AddedToken("__en__", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128023: AddedToken("__es__", rstrip=False, lstrip=False, single_word=False,

In [ ]:
text = "Guten Morgen! Wie geht es dir?"
result = train_pipeline1(text, forced_bos_token_id = train_pipeline1.tokenizer.get_lang_id("en"))
print(result)

[{'generated_text': 'Good morning, what is it?'}]


In [ ]:
reference = [
             ["Good morning! How are you?"]
]

In [ ]:
prediction = result[0]["generated_text"]
prediction

'Good morning, what is it?'

In [ ]:
score = bleu.compute(predictions=[prediction], references=[reference])
score

{'bleu': 0.0,
 'precisions': [0.2857142857142857, 0.0, 0.0, 0.0],
 'brevity_penalty': 0.6514390575310556,
 'length_ratio': 0.7,
 'translation_length': 7,
 'reference_length': 10}

In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM

In [ ]:
HELSINKI_MODEL = "Helsinki-NLP/opus-mt-de-hi"
HELSINKI_MODEL

'Helsinki-NLP/opus-mt-de-hi'

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(HELSINKI_MODEL)
tokenizer

OSError: Helsinki-NLP/opus-mt-de-hi is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [ ]:
model = TFAutoModelForSeq2SeqLM.from_pretrained(HELSINKI_MODEL)
model

OSError: Helsinki-NLP/opus-mt-de-hi is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [ ]:
text = "Good to see you!"

In [ ]:
input_ids = tokenizer.encode(text, return_tensors = "tf")
input_ids

NameError: name 'tokenizer' is not defined

In [ ]:
translated_ids = model.generate(
    input_ids,
    max_length = 50,
    num_beams = 4,
    early_stopping = True
)
translated_ids


NameError: name 'model' is not defined

In [ ]:
translated_text = tokenizer.decode(translated_ids[0], skip_special_tokens = True)
translated_text

NameError: name 'tokenizer' is not defined

In [ ]:
content = """
There were two brothers; the older one was always mean to the younger one.
The older one would chop firewood in the forest and sell it in the market.
One day, he stumbled across a magical tree.
The tree begged him not to cut him down and promised him golden apples in exchange.
The older brother felt disappointed with the number of apples he received.
He decided to cut down the tree anyway, but the tree showered him with hundreds of needles.
The boy was left lying on the forest ground in pain.
His younger brother finally found him and carefully took out every needle.
The older brother finally apologised for treating his brother badly. The magical tree saw this exchange.
It decided to give them more golden apples.
"""

In [ ]:
sum_pipeline = pipeline("summarization", model = "facebook/bart-large-cnn")
sum_pipeline

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [ ]:
help(sum_pipeline)

Help on SummarizationPipeline in module transformers.pipelines.text2text_generation object:

class SummarizationPipeline(Text2TextGenerationPipeline)
 |  SummarizationPipeline(*args, **kwargs)
 |  
 |  Summarize news articles and other documents.
 |  
 |  This summarizing pipeline can currently be loaded from [`pipeline`] using the following task identifier:
 |  `"summarization"`.
 |  
 |  The models that this pipeline can use are models that have been fine-tuned on a summarization task, which is
 |  currently, '*bart-large-cnn*', '*google-t5/t5-small*', '*google-t5/t5-base*', '*google-t5/t5-large*', '*google-t5/t5-3b*', '*google-t5/t5-11b*'. See the up-to-date
 |  list of available models on [huggingface.co/models](https://huggingface.co/models?filter=summarization). For a list
 |  of available parameters, see the [following
 |  documentation](https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.generation.GenerationMixin.generate)
 |  
 |  Usage:
 |  

In [ ]:
sum_pipeline(content)

[{'summary_text': 'The older brother would chop firewood in the forest and sell it in the market. One day, he stumbled across a magical tree. The tree begged him not to cut him down and promised him golden apples. The older brother felt disappointed with the number of apples he received. He decided to cut down the tree anyway.'}]

In [ ]:
results = sum_pipeline(content, max_length = 70, min_length = 30)
results[0]["summary_text"]

'The older brother was always mean to the younger one. The older one would chop firewood in the forest and sell it in the market. One day, he stumbled across a magical tree. The tree begged him not to cut him down.'

In [ ]:
sum_pipeline = pipeline("summarization", model = "Falconsai/text_summarization")
sum_pipeline

config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

In [ ]:
results = sum_pipeline(content, max_length = 70, min_length = 30)
results[0]["summary_text"]

'the older one would chop firewood in the forest and sell it in the market . One day, he stumbled across a magical tree . The tree begged him not to cut down the tree anyway, but the tree showedered him with hundreds of needles .'

# Sentence Similarity using Tokenizer and Model

In [ ]:
from transformers import AutoTokenizer, TFAutoModel
import numpy as np
import tensorflow as tf
from sklearn.metrics.pairwise import cosine_similarity

MODEL = "sentence-transformers/all-mpnet-base-v2"
MODEL

'sentence-transformers/all-mpnet-base-v2'

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL)
tokenizer

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


MPNetTokenizerFast(name_or_path='sentence-transformers/all-mpnet-base-v2', vocab_size=30527, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '[UNK]', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	104: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	30526: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, norm

In [ ]:
model = TFAutoModel.from_pretrained(MODEL, from_pt = True)
model

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFMPNetModel: ['embeddings.position_ids']
- This IS expected if you are initializing TFMPNetModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFMPNetModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFMPNetModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMPNetModel for predictions without further training.


In [ ]:
sentence1 = "I love cricket"
sentence2 = "Your hobby is travelling"


tokenized_input = tokenizer(
    [sentence1, sentence2],
    padding = True,
    truncation = True,
    return_tensors = "tf"
)

tokenized_input

{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[    0,  1049,  2297,  4537,     2,     1],
       [    0,  2119, 17796,  2007,  8936,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
output = model(**tokenized_input)
output

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-0.28195104,  0.09223691, -0.08653291, ...,  0.15852313,
         -0.0847178 , -0.03345417],
        [-0.26907647,  0.33373743, -0.05532368, ...,  0.3010539 ,
         -0.21100043,  0.02868585],
        [-0.33660424,  0.29722875, -0.00431338, ...,  0.30088696,
         -0.07253747, -0.02125322],
        [-0.27092484,  0.13506603, -0.13161306, ...,  0.12107079,
         -0.18619673, -0.00104517],
        [-0.26739085,  0.06087534, -0.08889519, ...,  0.18861282,
         -0.08054427, -0.02178362],
        [-0.29441175,  0.23567648, -0.10440856, ...,  0.24243364,
         -0.06808408, -0.0136544 ]],

       [[ 0.00270288,  0.09695998, -0.10058557, ...,  0.10203438,
          0.05122511, -0.1310883 ],
        [-0.06884971,  0.19828261, -0.08708052, ...,  0.15806296,
         -0.05293354, -0.03821013],
        [-0.06490474,  0.55857587, -0.06584415, ...,  0.1828303 ,
         -0.0272

In [ ]:
last_hidden_state = output.last_hidden_state
last_hidden_state

<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-0.28195104,  0.09223691, -0.08653291, ...,  0.15852313,
         -0.0847178 , -0.03345417],
        [-0.26907647,  0.33373743, -0.05532368, ...,  0.3010539 ,
         -0.21100043,  0.02868585],
        [-0.33660424,  0.29722875, -0.00431338, ...,  0.30088696,
         -0.07253747, -0.02125322],
        [-0.27092484,  0.13506603, -0.13161306, ...,  0.12107079,
         -0.18619673, -0.00104517],
        [-0.26739085,  0.06087534, -0.08889519, ...,  0.18861282,
         -0.08054427, -0.02178362],
        [-0.29441175,  0.23567648, -0.10440856, ...,  0.24243364,
         -0.06808408, -0.0136544 ]],

       [[ 0.00270288,  0.09695998, -0.10058557, ...,  0.10203438,
          0.05122511, -0.1310883 ],
        [-0.06884971,  0.19828261, -0.08708052, ...,  0.15806296,
         -0.05293354, -0.03821013],
        [-0.06490474,  0.55857587, -0.06584415, ...,  0.1828303 ,
         -0.02728964, -0.08839874],
        [-0.03400473,  0.14

In [ ]:
last_hidden_state.dtype

tf.float32

In [ ]:
mask = tf.cast(tokenized_input["attention_mask"], last_hidden_state.dtype)
mask

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tokenized_input["attention_mask"].dtype

tf.int32

In [ ]:
mask.dtype

tf.float32

In [ ]:
expanded_mask = tf.expand_dims(mask, -1)
expanded_mask

<tf.Tensor: shape=(2, 6, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
masked_embeddings = last_hidden_state * expanded_mask
masked_embeddings

<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-0.28195104,  0.09223691, -0.08653291, ...,  0.15852313,
         -0.0847178 , -0.03345417],
        [-0.26907647,  0.33373743, -0.05532368, ...,  0.3010539 ,
         -0.21100043,  0.02868585],
        [-0.33660424,  0.29722875, -0.00431338, ...,  0.30088696,
         -0.07253747, -0.02125322],
        [-0.27092484,  0.13506603, -0.13161306, ...,  0.12107079,
         -0.18619673, -0.00104517],
        [-0.26739085,  0.06087534, -0.08889519, ...,  0.18861282,
         -0.08054427, -0.02178362],
        [-0.        ,  0.        , -0.        , ...,  0.        ,
         -0.        , -0.        ]],

       [[ 0.00270288,  0.09695998, -0.10058557, ...,  0.10203438,
          0.05122511, -0.1310883 ],
        [-0.06884971,  0.19828261, -0.08708052, ...,  0.15806296,
         -0.05293354, -0.03821013],
        [-0.06490474,  0.55857587, -0.06584415, ...,  0.1828303 ,
         -0.02728964, -0.08839874],
        [-0.03400473,  0.14

In [ ]:
summed = tf.reduce_sum(masked_embeddings, axis = 1)
summed

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-1.4259474 ,  0.91914445, -0.36667824, ...,  1.0701475 ,
        -0.6349967 , -0.04885034],
       [-0.12394705,  1.2988136 , -0.6386689 , ...,  0.7197585 ,
         0.15097868, -0.5854893 ]], dtype=float32)>

In [ ]:
summed.shape

TensorShape([2, 768])

In [ ]:
summed_mask = tf.clip_by_value(tf.reduce_sum(mask, axis = 1),
                               clip_value_min = 1e-9,
                               clip_value_max= tf.reduce_max(mask, axis = 1))

summed_mask

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [ ]:
tf.reduce_max(mask, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [ ]:
tf.expand_dims(summed_mask, axis = -1)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [ ]:
mean_pooled = summed/ tf.expand_dims(summed_mask, axis = -1)
mean_pooled

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-1.4259474 ,  0.91914445, -0.36667824, ...,  1.0701475 ,
        -0.6349967 , -0.04885034],
       [-0.12394705,  1.2988136 , -0.6386689 , ...,  0.7197585 ,
         0.15097868, -0.5854893 ]], dtype=float32)>

In [ ]:
mean_pooled = mean_pooled.numpy()
similarity = cosine_similarity([mean_pooled[0], mean_pooled[1]])
similarity

array([[1.        , 0.29423824],
       [0.29423824, 1.0000001 ]], dtype=float32)